//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.27 at 12:05:46 PM IST 
//


package com.ms.ndcinstructions.transfer;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *         &lt;element name="productUPC" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *         &lt;element name="sourceLocationId" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *         &lt;element name="allocationError" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.marksandspencer.com/common/envelope/v2}unitDefinitions"/&gt;
 *         &lt;element ref="{http://www.marksandspencer.com/common/envelope/v2}sourceStock"/&gt;
 *         &lt;element name="destinations" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="destination" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="xDockLocationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="locationId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="intoStoreDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                             &lt;element name="onHandQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="allocationQuantity" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="allocationType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="unitDefinitionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="targetInventory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "productUPC",
    "sourceLocationId",
    "allocationError",
    "unitDefinitions",
    "sourceStock",
    "destinations"
})
@XmlRootElement(name = "allocationResponse")
public class AllocationResponse {

    @Override
	public String toString() {
		return "AllocationResponse [id=" + id + ", productUPC=" + productUPC + ", sourceLocationId=" + sourceLocationId
				+ ", allocationError=" + allocationError + ", unitDefinitions=" + unitDefinitions + ", sourceStock="
				+ sourceStock + ", destinations=" + destinations + "]";
	}


	@XmlElement(required = true)
    protected Object id;
    @XmlElement(required = true)
    protected Object productUPC;
    @XmlElement(required = true)
    protected Object sourceLocationId;
    protected Object allocationError;
    @XmlElement(required = true)
    protected UnitDefinitions unitDefinitions;
    @XmlElement(required = true)
    protected SourceStock sourceStock;
    protected AllocationResponse.Destinations destinations;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setId(Object value) {
        this.id = value;
    }

    /**
     * Gets the value of the productUPC property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getProductUPC() {
        return productUPC;
    }

    /**
     * Sets the value of the productUPC property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setProductUPC(Object value) {
        this.productUPC = value;
    }

    /**
     * Gets the value of the sourceLocationId property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSourceLocationId() {
        return sourceLocationId;
    }

    /**
     * Sets the value of the sourceLocationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSourceLocationId(Object value) {
        this.sourceLocationId = value;
    }

    /**
     * Gets the value of the allocationError property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAllocationError() {
        return allocationError;
    }

    /**
     * Sets the value of the allocationError property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAllocationError(Object value) {
        this.allocationError = value;
    }

    /**
     * Gets the value of the unitDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link UnitDefinitions }
     *     
     */
    public UnitDefinitions getUnitDefinitions() {
        return unitDefinitions;
    }

    /**
     * Sets the value of the unitDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitDefinitions }
     *     
     */
    public void setUnitDefinitions(UnitDefinitions value) {
        this.unitDefinitions = value;
    }

    /**
     * Gets the value of the sourceStock property.
     * 
     * @return
     *     possible object is
     *     {@link SourceStock }
     *     
     */
    public SourceStock getSourceStock() {
        return sourceStock;
    }

    /**
     * Sets the value of the sourceStock property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceStock }
     *     
     */
    public void setSourceStock(SourceStock value) {
        this.sourceStock = value;
    }

    /**
     * Gets the value of the destinations property.
     * 
     * @return
     *     possible object is
     *     {@link AllocationResponse.Destinations }
     *     
     */
    public AllocationResponse.Destinations getDestinations() {
        return destinations;
    }

    /**
     * Sets the value of the destinations property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllocationResponse.Destinations }
     *     
     */
    public void setDestinations(AllocationResponse.Destinations value) {
        this.destinations = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="destination" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="xDockLocationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="locationId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="intoStoreDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                   &lt;element name="onHandQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="allocationQuantity" maxOccurs="unbounded"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="allocationType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="unitDefinitionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="targetInventory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "destination"
    })
    public static class Destinations {

        @XmlElement(required = true)
        protected List<AllocationResponse.Destinations.Destination> destination;

        /**
         * Gets the value of the destination property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the destination property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDestination().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AllocationResponse.Destinations.Destination }
         * 
         * 
         */
        public List<AllocationResponse.Destinations.Destination> getDestination() {
            if (destination == null) {
                destination = new ArrayList<AllocationResponse.Destinations.Destination>();
            }
            return this.destination;
        }
        
        


        public void setDestination(List<AllocationResponse.Destinations.Destination> destination) {
			this.destination = destination;
		}




		/**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="xDockLocationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="locationId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="intoStoreDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *         &lt;element name="onHandQuantity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="allocationQuantity" maxOccurs="unbounded"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="allocationType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="unitDefinitionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="targetInventory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "xDockLocationId",
            "locationId",
            "intoStoreDate",
            "onHandQuantity",
            "allocationQuantity",
            "targetInventory"
        })
        public static class Destination {

            protected String xDockLocationId;
            @XmlElement(required = true)
            protected String locationId;
            @XmlElement(required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar intoStoreDate;
            @XmlElement(required = true)
            protected String onHandQuantity;
            @XmlElement(required = true)
            protected List<AllocationResponse.Destinations.Destination.AllocationQuantity> allocationQuantity;
            @XmlElement(required = true)
            protected String targetInventory;

            /**
             * Gets the value of the xDockLocationId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getXDockLocationId() {
                return xDockLocationId;
            }

            /**
             * Sets the value of the xDockLocationId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setXDockLocationId(String value) {
                this.xDockLocationId = value;
            }

            /**
             * Gets the value of the locationId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLocationId() {
                return locationId;
            }

            /**
             * Sets the value of the locationId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLocationId(String value) {
                this.locationId = value;
            }

            /**
             * Gets the value of the intoStoreDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getIntoStoreDate() {
                return intoStoreDate;
            }

            /**
             * Sets the value of the intoStoreDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setIntoStoreDate(XMLGregorianCalendar value) {
                this.intoStoreDate = value;
            }

            /**
             * Gets the value of the onHandQuantity property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOnHandQuantity() {
                return onHandQuantity;
            }

            /**
             * Sets the value of the onHandQuantity property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOnHandQuantity(String value) {
                this.onHandQuantity = value;
            }

            /**
             * Gets the value of the allocationQuantity property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the allocationQuantity property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAllocationQuantity().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link AllocationResponse.Destinations.Destination.AllocationQuantity }
             * 
             * 
             */
            public List<AllocationResponse.Destinations.Destination.AllocationQuantity> getAllocationQuantity() {
                if (allocationQuantity == null) {
                    allocationQuantity = new ArrayList<AllocationResponse.Destinations.Destination.AllocationQuantity>();
                }
                return this.allocationQuantity;
            }
            
            

            public void setAllocationQuantity(
					List<AllocationResponse.Destinations.Destination.AllocationQuantity> allocationQuantity) {
				this.allocationQuantity = allocationQuantity;
			}

			/**
             * Gets the value of the targetInventory property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTargetInventory() {
                return targetInventory;
            }

            /**
             * Sets the value of the targetInventory property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTargetInventory(String value) {
                this.targetInventory = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="allocationType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="unitDefinitionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "allocationType",
                "unitDefinitionId",
                "quantity"
            })
            public static class AllocationQuantity {

                @XmlElement(required = true)
                protected String allocationType;
                @XmlElement(required = true)
                protected String unitDefinitionId;
                protected int quantity;

                /**
                 * Gets the value of the allocationType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAllocationType() {
                    return allocationType;
                }

                /**
                 * Sets the value of the allocationType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAllocationType(String value) {
                    this.allocationType = value;
                }

                /**
                 * Gets the value of the unitDefinitionId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUnitDefinitionId() {
                    return unitDefinitionId;
                }

                /**
                 * Sets the value of the unitDefinitionId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUnitDefinitionId(String value) {
                    this.unitDefinitionId = value;
                }

                /**
                 * Gets the value of the quantity property.
                 * 
                 */
                public int getQuantity() {
                    return quantity;
                }

                /**
                 * Sets the value of the quantity property.
                 * 
                 */
                public void setQuantity(int value) {
                    this.quantity = value;
                }

            }

        }

    }

}
