//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.27 at 02:47:52 AM IST 
//

package com.ms.ndcinstructions.transfer;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import com.ms.ndcinstructions.transfer.sapHeader.IntegrationExtensionType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Header", propOrder = {
		"envelopeVersion",
		"language",
		"messageId",
		"correlationId",
		"createdTimestamp",
		"sequenceId",
		"sourceApplicationName",
		"interfaceId",
		"interfaceName",
		"payloadName",
		"batchMessageCount",
		"batchRecordCount",
		"integrationExtension",
})
public class SAPHeader {

	@XmlElement(name = "EnvelopeVersion", defaultValue = "2.0")
	protected String envelopeVersion;
	@XmlElement(name = "Language")
	protected String language;
	@XmlElement(name = "MessageId", required = true)
	protected String messageId;
    @XmlElement(name = "CorrelationId")
    protected String correlationId;
	@XmlElement(name = "CreatedTimestamp", required = true)
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar createdTimestamp;
	@XmlElement(name = "SequenceId")
	protected BigInteger sequenceId;
	@XmlElement(name = "SourceApplicationName", required = true)
	protected String sourceApplicationName;
	@XmlElement(name = "InterfaceId", required = true)
	protected String interfaceId;
	@XmlElement(name = "InterfaceName")
	protected String interfaceName;
	@XmlElement(name = "PayloadName", required = true)
	protected String payloadName;
	@XmlElement(name = "BatchMessageCount")
	protected int batchMessageCount;
	@XmlElement(name = "BatchRecordCount")
	protected int batchRecordCount;
	@XmlElement(name = "IntegrationExtension", namespace="marksspencer.com/is/2009/schemas/envelope/")
	protected IntegrationExtensionType integrationExtension;

	
	
	
	public String getCorrelationId() {
		return correlationId;
	}


	public void setCorrelationId(String correlationId) {
		this.correlationId = correlationId;
	}


	public String getEnvelopeVersion() {
		return envelopeVersion;
	}

	
	public void setEnvelopeVersion(String value) {
		this.envelopeVersion = value;
	}


	public String getLanguage() {
		return language;
	}


	public void setLanguage(String value) {
		this.language = value;
	}


	public String getMessageId() {
		return messageId;
	}


	public void setMessageId(String value) {
		this.messageId = value;
	}


	public XMLGregorianCalendar getCreatedTimestamp() {
		return createdTimestamp;
	}

	public void setCreatedTimestamp(XMLGregorianCalendar value) {
		this.createdTimestamp = value;
	}

	public BigInteger getSequenceId() {
		return sequenceId;
	}

	public void setSequenceId(BigInteger value) {
		this.sequenceId = value;
	}

	public String getSourceApplicationName() {
		return sourceApplicationName;
	}

	public void setSourceApplicationName(String value) {
		this.sourceApplicationName = value;
	}

	public String getInterfaceId() {
		return interfaceId;
	}

	public void setInterfaceId(String value) {
		this.interfaceId = value;
	}

	public String getInterfaceName() {
		return interfaceName;
	}


	public void setInterfaceName(String value) {
		this.interfaceName = value;
	}


	public String getPayloadName() {
		return payloadName;
	}


	public void setPayloadName(String value) {
		this.payloadName = value;
	}


	public int getBatchMessageCount() {
		return batchMessageCount;
	}

	public void setBatchMessageCount(int value) {
		this.batchMessageCount = value;
	}

	public int getBatchRecordCount() {
		return batchRecordCount;
	}

	public void setBatchRecordCount(int value) {
		this.batchRecordCount = value;
	}

	public IntegrationExtensionType getIntegrationExtension() {
		return integrationExtension;
	}


	public void setIntegrationExtension(IntegrationExtensionType integrationExtension) {
		this.integrationExtension = integrationExtension;
	}
	
}
